services:
  api:
    image: node:18  # same base as ulixee cloud
    command: bash -c "npm install && npm run start"
    ports:
      - "3000:3000"
      - "9229:9229"
    working_dir: /app/api
    volumes:
      - ./:/app/api
    depends_on:
      - core
      - httpbin
  core:
    image: ulixee/ulixee-cloud:latest
    ports:
      - "1818:1818"
    restart: on-failure
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8000:80"
